//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceProfile) DeepCopyInto(out *ComplianceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ComplianceProfile.
func (in *ComplianceProfile) DeepCopy() *ComplianceProfile {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *ComplianceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceProfileList) DeepCopyInto(out *ComplianceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComplianceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ComplianceProfileList.
func (in *ComplianceProfileList) DeepCopy() *ComplianceProfileList {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *ComplianceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceProfileSpec) DeepCopyInto(out *ComplianceProfileSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ComplianceProfileSpec.
func (in *ComplianceProfileSpec) DeepCopy() *ComplianceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceProfileStatus) DeepCopyInto(out *ComplianceProfileStatus) {
	*out = *in
}

// DeepCopy creates a deep copy of ComplianceProfileStatus.
func (in *ComplianceProfileStatus) DeepCopy() *ComplianceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy creates a deep copy of Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *Finding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *FindingList) DeepCopyInto(out *FindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Finding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of FindingList.
func (in *FindingList) DeepCopy() *FindingList {
	if in == nil {
		return nil
	}
	out := new(FindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *FindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *FindingSpec) DeepCopyInto(out *FindingSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of FindingSpec.
func (in *FindingSpec) DeepCopy() *FindingSpec {
	if in == nil {
		return nil
	}
	out := new(FindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceAudit) DeepCopyInto(out *ComplianceAudit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ComplianceAudit.
func (in *ComplianceAudit) DeepCopy() *ComplianceAudit {
	if in == nil {
		return nil
	}
	out := new(ComplianceAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *ComplianceAudit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceAuditList) DeepCopyInto(out *ComplianceAuditList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComplianceAudit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ComplianceAuditList.
func (in *ComplianceAuditList) DeepCopy() *ComplianceAuditList {
	if in == nil {
		return nil
	}
	out := new(ComplianceAuditList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *ComplianceAuditList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceAuditSpec) DeepCopyInto(out *ComplianceAuditSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ComplianceAuditSpec.
func (in *ComplianceAuditSpec) DeepCopy() *ComplianceAuditSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceAuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceAuditStatus) DeepCopyInto(out *ComplianceAuditStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy creates a deep copy of ComplianceAuditStatus.
func (in *ComplianceAuditStatus) DeepCopy() *ComplianceAuditStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceAuditStatus)
	in.DeepCopyInto(out)
	return out
}
