apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-dns-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gcp-dns-credentials
    creationPolicy: Owner
  data:
    - secretKey: service-account.json
      remoteRef:
        key: cert-manager/gcp
        property: service_account_json
