apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-linode
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.19.0
    helm:
      values: |
        provider: linode
        policy: upsert-only
        registry: txt
        txtOwnerId: mantl-prod
        extraEnv:
          - name: LINODE_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: linode-api-token
                key: token
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
