apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spinnaker-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/armory/spinnaker-operator
    targetRevision: v1.2.0
    path: deploy
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: spinnaker-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
