apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger
spec:
  interval: 30m
  chart:
    spec:
      chart: flagger
      version: "1.38.x"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      interval: 12h

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: flagger-config
      valuesKey: values.yaml
