apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chaos-mesh
resources:
  - namespace.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: chaos-mesh-config
    files:
      - values.yaml
