---
# yamllint disable rule:line-length
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
    groups:
      github-actions-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directories:
      - /
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
    groups:
      gomod-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    directories:
      - /
      - /examples/**
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
    groups:
      pip-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: terraform
    directories:
      - /infra/terraform/blueprints/*
      - /infra/terraform/modules/*
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
    groups:
      terraform-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directories:
      - /
      - /examples/**
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
    groups:
      docker-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directories:
      - /examples/ecommerce-microservices/src/frontend
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
    groups:
      npm-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
