apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: mantl-examples
automountServiceAccountToken: true
