repos:
  - repo: local
    hooks:
      - id: kyverno-no-placeholders
        name: kyverno-no-placeholders
        entry: scripts/check-placeholders.sh
        language: system
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 24.12.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.12.2
    hooks:
      - id: ansible-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
