apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azuredns-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: azuredns-credentials
    creationPolicy: Owner
  data:
    - secretKey: tenantId
      remoteRef:
        key: cert-manager/azure
        property: tenant_id
    - secretKey: clientId
      remoteRef:
        key: cert-manager/azure
        property: client_id
    - secretKey: clientSecret
      remoteRef:
        key: cert-manager/azure
        property: client_secret
    - secretKey: subscriptionId
      remoteRef:
        key: cert-manager/azure
        property: subscription_id
    - secretKey: resourceGroupName
      remoteRef:
        key: cert-manager/azure
        property: resource_group
    - secretKey: hostedZoneName
      remoteRef:
        key: cert-manager/azure
        property: hosted_zone
