apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spinnaker-ingress
  namespace: spinnaker
spec:
  tls:
    - hosts:
        - deck.example.com
      secretName: deck-tls
    - hosts:
        - gate.example.com
      secretName: gate-tls
