apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "mantl-platform.namespace" . }}
  labels:
    {{- include "mantl-platform.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  {{- with .Values.namespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
