apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-clouddriver
  namespace: spinnaker
spec:
  template:
    spec:
      containers:
        - name: clouddriver
          env:
            - name: REGISTRY
              valueFrom:
                secretKeyRef:
                  name: spinnaker-docker-registry
                  key: registry
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: spinnaker-docker-registry
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spinnaker-docker-registry
                  key: password
