apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
  namespace: spinnaker
spec:
  spinnakerConfig:
    config:
      secretManagement:
        type: kubernetes
        enabled: true
      persistentStorage:
        gcs:
          bucket: TODO_GCS_BUCKET
          rootFolder: front50
          project: TODO_GCP_PROJECT
          # Read GCP SA JSON from K8s Secret using encryptedFile reference
          jsonPath: encryptedFile:k8s!n:spinnaker!s:front50-gcs!k:service-account.json
      artifacts:
        dockerRegistry:
          accounts:
            - name: dockerhub
              address: https://index.docker.io
              repositories: []
              username: ${DOCKER_USERNAME}
              password: ${DOCKER_PASSWORD}
        github:
          enabled: true
          accounts:
            - name: github
              token: encrypted:k8s!n:spinnaker!s:github-artifacts!k:token
        gitRepo:
          enabled: true
          accounts:
            - name: github-repo
              token: encrypted:k8s!n:spinnaker!s:github-artifacts!k:token
              gitRepoType: GITHUB
              endpoint: https://github.com
