apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gate-oidc
  namespace: spinnaker
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gate-oidc
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: spinnaker/gate/oidc
        property: client_id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: spinnaker/gate/oidc
        property: client_secret
