apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-gate
  namespace: spinnaker
spec:
  template:
    spec:
      containers:
        - name: gate
          envFrom:
            - secretRef:
                name: gate-oidc
