apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      gate:
        server:
          servlet:
            context-path: /
        security:
          basic:
            enabled: false
          oauth2:
            enabled: true
            client:
              clientId: ${OIDC_CLIENT_ID}
              clientSecret: ${OIDC_CLIENT_SECRET}
              accessTokenUri: https://OIDC_ISSUER_DOMAIN/oauth/token
              userAuthorizationUri: https://OIDC_ISSUER_DOMAIN/authorize
              scope: openid profile email
            resource:
              userInfoUri: https://OIDC_ISSUER_DOMAIN/userinfo
            provider:
              userInfoMapping:
                email: email
                firstName: given_name
                lastName: family_name
                username: email
