apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: digitalocean-dns
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cert-manager/digitalocean
        property: api_token
