package compiler

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"

	"github.com/thomasvincent/mantl/apis/platform/v1alpha1"
	"sigs.k8s.io/yaml"
)

// Artifact identifies exact generated bytes. Content is deliberately excluded
// from JSON reports; reports describe desired state rather than observed health.
type Artifact struct {
	Path    string `json:"path"`
	SHA256  string `json:"sha256"`
	Size    int    `json:"size"`
	Content []byte `json:"-"`
}

// Plan is an offline, deterministic compiler result. Hashes are integrity
// identifiers, not signatures or deployment acceptance evidence.
type Plan struct {
	SpecSHA256    string               `json:"specSHA256"`
	SchemaVersion string               `json:"schemaVersion"`
	Platform      string               `json:"platform"`
	Provider      string               `json:"provider"`
	Distribution  string               `json:"distribution"`
	Applications  []PlannedApplication `json:"applications"`
	Artifacts     []Artifact           `json:"artifacts"`
	Notices       []string             `json:"notices"`
}

type PlannedApplication struct {
	Name       string `json:"name"`
	Path       string `json:"path"`
	Repository string `json:"repository"`
	Revision   string `json:"revision"`
}

// Compile validates and renders all artifacts without reading or writing files,
// contacting a cluster, invoking tools or changing its input.
func Compile(cluster *v1alpha1.MantlCluster) (Plan, error) {
	if err := Validate(cluster); err != nil {
		return Plan{}, fmt.Errorf("validate platform: %w", err)
	}
	plan := Plan{
		SchemaVersion: PlanSchemaVersion, Platform: cluster.Name,
		Provider: cluster.Spec.Provider.Kind, Distribution: cluster.Spec.Kubernetes.Distribution,
		Applications: []PlannedApplication{}, Artifacts: []Artifact{},
		Notices: []string{"Offline compilation does not verify repository contents, infrastructure changes, cluster health or compliance.", "Bootstrap applies selected Applications; removed Applications require a reviewed GitOps cleanup."},
	}
	identity, err := json.Marshal(planSpecIdentity{Name: cluster.Name, Spec: cluster.Spec})
	if err != nil {
		return Plan{}, fmt.Errorf("hash platform spec: %w", err)
	}
	hash := sha256.Sum256(identity)
	plan.SpecSHA256 = hex.EncodeToString(hash[:])

	terraform, err := terraformManifest(cluster)
	if err != nil {
		return Plan{}, err
	}
	plan.add("terraform.tfvars.json", terraform)
	for _, app := range GitOpsApplications(cluster) {
		data, err := applicationManifest(app.Name, app.Path, app.Repository, app.Revision)
		if err != nil {
			return Plan{}, err
		}
		plan.add("gitops/"+app.Name+".yaml", data)
		plan.Applications = append(plan.Applications, PlannedApplication(app))
	}
	if err := plan.compileTenants(cluster); err != nil {
		return Plan{}, err
	}
	if cluster.Spec.GitOps.Revision == "" || cluster.Spec.GitOps.Revision == "main" {
		plan.Notices = append(plan.Notices, "GitOps follows main; artifact hashes do not pin the referenced repository contents.")
	}
	sort.Slice(plan.Artifacts, func(i, j int) bool { return plan.Artifacts[i].Path < plan.Artifacts[j].Path })
	if err := ValidatePlan(plan); err != nil {
		return Plan{}, err
	}
	return plan, nil
}

func (plan *Plan) compileTenants(cluster *v1alpha1.MantlCluster) error {
	if len(cluster.Spec.Tenants) == 0 && cluster.Spec.GitOps.TenantPath == "" {
		return nil
	}
	names := []string{}
	for _, tenant := range cluster.Spec.Tenants {
		data, err := tenantManifest(tenant, tenantEnvironment(cluster))
		if err != nil {
			return err
		}
		plan.add("tenants/"+tenant.Name+".yaml", data)
		names = append(names, tenant.Name+".yaml")
	}
	data, err := yaml.Marshal(map[string]interface{}{"apiVersion": "kustomize.config.k8s.io/v1beta1", "kind": "Kustomization", "resources": names})
	if err != nil {
		return fmt.Errorf("render tenant index: %w", err)
	}
	plan.add("tenants/kustomization.yaml", data)
	plan.Notices = append(plan.Notices, "Commit generated tenants at gitops.tenantPath before bootstrap; files omitted from the tenant index are inactive.")
	return nil
}

func (plan *Plan) add(path string, data []byte) {
	hash := sha256.Sum256(data)
	plan.Artifacts = append(plan.Artifacts, Artifact{Path: path, SHA256: hex.EncodeToString(hash[:]), Size: len(data), Content: data})
}

type planSpecIdentity struct {
	Name string                    `json:"name"`
	Spec v1alpha1.MantlClusterSpec `json:"spec"`
}
