apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linode-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: linode-api-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: external-dns/linode
        property: api_token
