apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/cert-manager.yaml
  - apps/cert-manager-clusterissuers.yaml
  - apps/external-secrets.yaml
  - apps/kyverno.yaml
  - apps/kyverno-policies.yaml
  - apps/prometheus.yaml
  - apps/tempo.yaml
