apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: route53-credentials
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: cert-manager/route53
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: cert-manager/route53
        property: aws_secret_access_key
