apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: hello-domain
    literals:
      - domain=app.example.com
replacements:
  - source:
      kind: ConfigMap
      name: hello-domain
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          name: app
        fieldPaths:
          - spec.rules.0.host
        options:
          create: false
