apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../
  - ../../../production/apps/cert-manager-issuer-dns-azure.yaml
  - ../../../production/apps/external-dns-azure.yaml
  - ../../../production/apps/gateway-sample.yaml
  - ../../../production/apps/example-hello.yaml
