# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    opencost.io/team: platform
    opencost.io/project: mantl
    environment: production
  name: mantl-compliance-system
