# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-operator-controller-manager
  namespace: mantl-compliance-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-operator-manager-role
rules:
  - apiGroups:
      - compliance.mantl.io
    resources:
      - complianceprofiles
      - complianceprofiles/status
      - complianceaudits
      - complianceaudits/status
      - findings
      - findings/status
      - auditruns
      - auditruns/status
      - controlevaluations
      - controlevaluations/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - compliance.mantl.io
    resources:
      - complianceexceptions
      - complianceexceptions/status
    verbs: [get, list, watch]
  - apiGroups:
      - batch
    resources: [jobs]
    verbs: [get, list, watch, create]
  - apiGroups: ['']
    resources: [namespaces]
    resourceNames: [kube-system]
    verbs: [get]
  - apiGroups:
      - wgpolicyk8s.io
    resources:
      - policyreports
      - clusterpolicyreports
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - services
      - serviceaccounts
    verbs:
      - get
      - list
  - apiGroups: ['']
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups:
      - kyverno.io
    resources:
      - clusterpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compliance-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: compliance-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: compliance-operator-controller-manager
    namespace: mantl-compliance-system
