apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-operator-controller-manager
  namespace: mantl-compliance-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-operator-manager-role
rules:
- apiGroups: ["compliance.mantl.io"]
  resources: ["complianceprofiles", "complianceprofiles/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["kyverno.io"]
  resources: ["clusterpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compliance-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: compliance-operator-manager-role
subjects:
- kind: ServiceAccount
  name: compliance-operator-controller-manager
  namespace: mantl-compliance-system
