apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spinnaker-ghcr-registry
  namespace: spinnaker
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: spinnaker-ghcr-registry
    creationPolicy: Owner
  data:
    - secretKey: registry
      remoteRef:
        key: spinnaker/ghcr
        property: registry
    - secretKey: username
      remoteRef:
        key: spinnaker/ghcr
        property: username
    - secretKey: password
      remoteRef:
        key: spinnaker/ghcr
        property: token
