apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-app-secret
  labels:
    app.kubernetes.io/name: database-app
    app.kubernetes.io/component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default-secret-store
    kind: SecretStore
  target:
    name: database-app-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: database-app/username
    - secretKey: password
      remoteRef:
        key: database-app/password
