apiVersion: v1
kind: Namespace
metadata:
  name: apps-dev # change as needed
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spin-sa
  namespace: apps-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spin-role
  namespace: apps-dev
rules:
  - apiGroups: ["", "apps", "batch", "extensions", "autoscaling", "policy"]
    resources: ["pods","pods/log","replicasets","deployments","services","secrets","configmaps","ingresses","cronjobs","jobs"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spin-rb
  namespace: apps-dev
subjects:
  - kind: ServiceAccount
    name: spin-sa
    namespace: apps-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spin-role
