apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spinnaker-docker-registry
  namespace: spinnaker
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: spinnaker-docker-registry
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: spinnaker/docker-registry
        property: username
    - secretKey: password
      remoteRef:
        key: spinnaker/docker-registry
        property: password
    - secretKey: registry
      remoteRef:
        key: spinnaker/docker-registry
        property: registry
