//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *AttestationSpec) DeepCopyInto(out *AttestationSpec) {
	*out = *in
	in.AttestedAt.DeepCopyInto(&out.AttestedAt)
}

// DeepCopy creates a deep copy of AttestationSpec.
func (in *AttestationSpec) DeepCopy() *AttestationSpec {
	if in == nil {
		return nil
	}
	out := new(AttestationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceAudit) DeepCopyInto(out *ComplianceAudit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ComplianceAudit.
func (in *ComplianceAudit) DeepCopy() *ComplianceAudit {
	if in == nil {
		return nil
	}
	out := new(ComplianceAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *ComplianceAudit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceAuditSpec) DeepCopyInto(out *ComplianceAuditSpec) {
	*out = *in
	if in.ReportFormats != nil {
		in, out := &in.ReportFormats, &out.ReportFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of ComplianceAuditSpec.
func (in *ComplianceAuditSpec) DeepCopy() *ComplianceAuditSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceAuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceAuditStatus) DeepCopyInto(out *ComplianceAuditStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.CompletionTime.DeepCopyInto(&out.CompletionTime)
	if in.ReportURLs != nil {
		in, out := &in.ReportURLs, &out.ReportURLs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FindingRefs != nil {
		in, out := &in.FindingRefs, &out.FindingRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of ComplianceAuditStatus.
func (in *ComplianceAuditStatus) DeepCopy() *ComplianceAuditStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceAuditStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceFramework) DeepCopyInto(out *ComplianceFramework) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ComplianceFramework.
func (in *ComplianceFramework) DeepCopy() *ComplianceFramework {
	if in == nil {
		return nil
	}
	out := new(ComplianceFramework)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *ComplianceFramework) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceFrameworkSpec) DeepCopyInto(out *ComplianceFrameworkSpec) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]ControlCategory, len(*in))
		copy(*out, *in)
	}
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]Control, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ComplianceFrameworkSpec.
func (in *ComplianceFrameworkSpec) DeepCopy() *ComplianceFrameworkSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceFrameworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceFrameworkStatus) DeepCopyInto(out *ComplianceFrameworkStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy creates a deep copy of ComplianceFrameworkStatus.
func (in *ComplianceFrameworkStatus) DeepCopy() *ComplianceFrameworkStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceFrameworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceProfile) DeepCopyInto(out *ComplianceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ComplianceProfile.
func (in *ComplianceProfile) DeepCopy() *ComplianceProfile {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *ComplianceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceProfileSpec) DeepCopyInto(out *ComplianceProfileSpec) {
	*out = *in
	if in.IncludeControls != nil {
		in, out := &in.IncludeControls, &out.IncludeControls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeControls != nil {
		in, out := &in.ExcludeControls, &out.ExcludeControls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.EvidenceStore.DeepCopyInto(&out.EvidenceStore)
	if in.NotificationChannels != nil {
		in, out := &in.NotificationChannels, &out.NotificationChannels
		*out = make([]NotificationChannel, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of ComplianceProfileSpec.
func (in *ComplianceProfileSpec) DeepCopy() *ComplianceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ComplianceProfileStatus) DeepCopyInto(out *ComplianceProfileStatus) {
	*out = *in
	in.LastAudit.DeepCopyInto(&out.LastAudit)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ComplianceProfileStatus.
func (in *ComplianceProfileStatus) DeepCopy() *ComplianceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *Control) DeepCopyInto(out *Control) {
	*out = *in
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]ControlMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of Control.
func (in *Control) DeepCopy() *Control {
	if in == nil {
		return nil
	}
	out := new(Control)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ControlCategory) DeepCopyInto(out *ControlCategory) {
	*out = *in
}

// DeepCopy creates a deep copy of ControlCategory.
func (in *ControlCategory) DeepCopy() *ControlCategory {
	if in == nil {
		return nil
	}
	out := new(ControlCategory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ControlMapping) DeepCopyInto(out *ControlMapping) {
	*out = *in
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(PolicyReference)
		(*in).DeepCopyInto(*out)
	}
	if in.EvidenceCollector != nil {
		in, out := &in.EvidenceCollector, &out.EvidenceCollector
		*out = new(EvidenceCollectorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of ControlMapping.
func (in *ControlMapping) DeepCopy() *ControlMapping {
	if in == nil {
		return nil
	}
	out := new(ControlMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *EvidenceCollectorSpec) DeepCopyInto(out *EvidenceCollectorSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of EvidenceCollectorSpec.
func (in *EvidenceCollectorSpec) DeepCopy() *EvidenceCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(EvidenceCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *EvidenceSpec) DeepCopyInto(out *EvidenceSpec) {
	*out = *in
	in.CollectedAt.DeepCopyInto(&out.CollectedAt)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
	if in.Attestation != nil {
		in, out := &in.Attestation, &out.Attestation
		*out = new(AttestationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of EvidenceSpec.
func (in *EvidenceSpec) DeepCopy() *EvidenceSpec {
	if in == nil {
		return nil
	}
	out := new(EvidenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *EvidenceStatus) DeepCopyInto(out *EvidenceStatus) {
	*out = *in
	in.VerifiedAt.DeepCopyInto(&out.VerifiedAt)
}

// DeepCopy creates a deep copy of EvidenceStatus.
func (in *EvidenceStatus) DeepCopy() *EvidenceStatus {
	if in == nil {
		return nil
	}
	out := new(EvidenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *EvidenceStoreSpec) DeepCopyInto(out *EvidenceStoreSpec) {
	*out = *in
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(EncryptionSpec)
		**out = **in
	}
}

// DeepCopy creates a deep copy of EvidenceStoreSpec.
func (in *EvidenceStoreSpec) DeepCopy() *EvidenceStoreSpec {
	if in == nil {
		return nil
	}
	out := new(EvidenceStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *EncryptionSpec) DeepCopyInto(out *EncryptionSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of EncryptionSpec.
func (in *EncryptionSpec) DeepCopy() *EncryptionSpec {
	if in == nil {
		return nil
	}
	out := new(EncryptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *Evidence) DeepCopyInto(out *Evidence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of Evidence.
func (in *Evidence) DeepCopy() *Evidence {
	if in == nil {
		return nil
	}
	out := new(Evidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *Evidence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *Finding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *FindingSpec) DeepCopyInto(out *FindingSpec) {
	*out = *in
	out.Resource = in.Resource
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make([]EvidenceItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Remediation = in.Remediation
}

// DeepCopy creates a deep copy of FindingSpec.
func (in *FindingSpec) DeepCopy() *FindingSpec {
	if in == nil {
		return nil
	}
	out := new(FindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *FindingStatus) DeepCopyInto(out *FindingStatus) {
	*out = *in
	in.DueDate.DeepCopyInto(&out.DueDate)
	in.ResolvedAt.DeepCopyInto(&out.ResolvedAt)
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]FindingHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of FindingStatus.
func (in *FindingStatus) DeepCopy() *FindingStatus {
	if in == nil {
		return nil
	}
	out := new(FindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *FindingHistoryEntry) DeepCopyInto(out *FindingHistoryEntry) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy creates a deep copy of FindingHistoryEntry.
func (in *FindingHistoryEntry) DeepCopy() *FindingHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(FindingHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *EvidenceItem) DeepCopyInto(out *EvidenceItem) {
	*out = *in
	in.CollectedAt.DeepCopyInto(&out.CollectedAt)
}

// DeepCopy creates a deep copy of EvidenceItem.
func (in *EvidenceItem) DeepCopy() *EvidenceItem {
	if in == nil {
		return nil
	}
	out := new(EvidenceItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *NotificationChannel) DeepCopyInto(out *NotificationChannel) {
	*out = *in
}

// DeepCopy creates a deep copy of NotificationChannel.
func (in *NotificationChannel) DeepCopy() *NotificationChannel {
	if in == nil {
		return nil
	}
	out := new(NotificationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *PolicyReference) DeepCopyInto(out *PolicyReference) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy creates a deep copy of PolicyReference.
func (in *PolicyReference) DeepCopy() *PolicyReference {
	if in == nil {
		return nil
	}
	out := new(PolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *RemediationSpec) DeepCopyInto(out *RemediationSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of RemediationSpec.
func (in *RemediationSpec) DeepCopy() *RemediationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy creates a deep copy of ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}
