apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spinnaker
resources:
  - ../overlays/oidc/externalsecret.yaml
  - ../accounts/docker/externalsecret.yaml
  - ../accounts/ecr/externalsecret.yaml
  - ../accounts/gcr/externalsecret.yaml
  - ../accounts/ghcr/externalsecret.yaml
