apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencost

resources:
  - namespace.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: opencost-config
    files:
      - values.yaml
