apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../
  - ../../apps/external-dns-azure-wi.yaml

configMapGenerator:
  - name: wi-config
    literals:
      - uamiClientId=REPLACE_WITH_UAMI_CLIENT_ID

replacements:
  - source:
      kind: ConfigMap
      name: wi-config
      fieldPath: data.uamiClientId
    targets:
      - select:
          kind: Application
          name: external-dns-azure-wi
        fieldPaths:
          - spec.source.helm.parameters.0.value
