apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
  namespace: spinnaker
spec:
  spinnakerConfig:
    config:
      secretManagement:
        type: kubernetes
        enabled: true
      persistentStorage:
        s3:
          bucket: TODO_S3_BUCKET
          rootFolder: front50
          region: TODO_AWS_REGION
          accessKeyId: encrypted:k8s!n:spinnaker!s:front50-s3!k:accessKeyId
          secretAccessKey: encrypted:k8s!n:spinnaker!s:front50-s3!k:secretAccessKey
      artifacts:
        dockerRegistry:
          accounts:
            - name: dockerhub
              address: https://index.docker.io
              repositories: [] # e.g., yourorg/yourapp
              username: ${DOCKER_USERNAME}
              password: ${DOCKER_PASSWORD}
        github:
          enabled: true
          accounts:
            - name: github
              token: encrypted:k8s!n:spinnaker!s:github-artifacts!k:token
        gitRepo:
          enabled: true
          accounts:
            - name: github-repo
              token: encrypted:k8s!n:spinnaker!s:github-artifacts!k:token
              gitRepoType: GITHUB
              endpoint: https://github.com
