apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
description: Vault backend for External Secrets Operator
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
